### PR TITLE
Qos-Metering support

### PR DESCRIPTION
**Pull request by amarsri28**
- Includes preliminary class structure for supporting qos-metering

- Explicitly kept disabled code sections for now

### CODE REVIEW

**Comment by krsna1729** [comment]
Patch format is currently being used update existing files in upstream. If you are creating new files you can place it directly in our repo. They will be copied during the build.

**Comment by amarsri28** [comment]
under implementation

**Review by amarsri28 — COMMENTED** [review]
copyright updates in files

**Comment by amarsri28** [comment]
It is expected that Control path update will enable pipeline in up4.bess when its ready.

**Review by amarsri28 — COMMENTED** [review]
it is expected that control path changes will update pipeline in up4.bess . license update, code optimizations added

**Comment by krsna1729** [comment]
Superceded by #310

**Comment by amarsri28** [comment]
Opening for providing detail comments :
-->this PR contains basic architecture of Qos module & providing support for various metering algorithm.
--> interaction with slow path
--> Created first test case and tested through it (metering.bess)

Code has been taken and merged in other PR.

**Pull request closed without merging**
