### PR TITLE
BESS: fix checksum offload in bess patch

### PR DESCRIPTION
**Pull request by yipwork**
This commit enables the UDP rx checksum which was missing
in previous BESS patch.
It also fixes the hw_ inilization value.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by krsna1729** [comment]
test this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by hyunsun** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Review by krsna1729 — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by krsna1729** [comment]
retest this please

**Pull request merged**
