### PR TITLE
Bump go-pfcp to v0.0.14

### PR DESCRIPTION
**Pull request by ccascone**
Includes fix for `GateStatusDL` reported in #384: https://github.com/wmnsk/go-pfcp/pull/91

### CODE REVIEW

**Comment by krsna1729** [comment]
No issue with this bump itself but have a question - seems like go-pfcp should not have been changed?

image

**Review by krsna1729 — DISMISSED** [review]

**Review by osinstom — DISMISSED** [review]

**Comment by ccascone** [comment]
> No issue with this bump itself but have a question - seems like go-pfcp should have been changed to `& 0x03`?
> 

Ah, yes... I missed that part about future uses. I'm going ahead and merge this to avoid the corrupted decoding. I will also push anew change to `go-pfcp`.

**Comment by krsna1729** [comment]
FYI Upstream has been merged. Either its retagged as v0.0.13 or you will have to update go.mod to master. I guess the interpreting anything other than open as closed logic is already there in pfcpiface now, correct?

**Comment by krsna1729** [comment]
seems like the interpretation was done in bess.go layer instead of pfcp layer

**Comment by krsna1729** [comment]
Bump to v0.0.14

**Review by krsna1729 — APPROVED** [review]

**Pull request merged**
