### PR TITLE
Use Set for tunnelPeerIDsPool and applicationIDsPool

### PR DESCRIPTION
**Pull request by Adityav369**
Converted tunnelPeerIdsPool and applicationIDsPool from lists to sets. Added a check for allocated == nil.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Review by osinstom — DISMISSED** [review]
LGTM, waiting for CI to pass

**Comment by osinstom** [comment]
@Adityav369 you should also fix integration tests now

**Pull request closed without merging**
