### PR TITLE
HeartBeat Timer Implementation 

### PR DESCRIPTION
**Pull request by akhila-s06**
Raising new pull request off PR # [328](https://github.com/omec-project/upf-epc/pull/328).

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Review by krsna1729 — APPROVED** [review]

**Comment by krsna1729** [comment]
test this please

**Comment by krsna1729** [comment]
@akhila-s06 can you format go code? There seems to be diff after go fmt
https://github.com/omec-project/upf-epc/runs/4429492718?check_suite_focus=true#step:9:1

**Comment by krsna1729** [comment]
@akhila-s06 I pushed the format update and squashed the commits

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Review by krsna1729 — APPROVED** [review]

**Review by krsna1729 — APPROVED** [review]

**Comment by krsna1729** [comment]
retest this please

**Pull request merged**
