### PR TITLE
Copy modules folder for bessd to load .so files

### PR DESCRIPTION
**Pull request by krsna1729**
I0622 03:01:52.720116     1 bessd.cc:456] Loading plugin (attempt 1): /bin/modules/sequential_update.so

RoundRobin       splits packets evenly with round robin
SequentialUpdate updates packet data sequentially in a range
SetMetadata      Set metadata attributes to packets

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
