### PR TITLE
Fix: pfcpsim connection refused

### PR DESCRIPTION
**Pull request by krsna1729**
- Remove default config pointing to 172.17.0.1. UPF listens on 0.0.0.0
- Remove flag parsing from pfcpsim

Fixes: #256 

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
we still have this issue
```
$ docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -pfcpsim
2021/04/17 06:26:16 main.go:127: { 64 {access} {core} {  spgwc false 10.250.0.0/16 8080} {172.17.0.1/32 onos 51001 10.250.0.0/24} false {16.0.0.1 11.1.1.129 13.1.1.199 6.6.6.6 9.9.9.9 0x30000000 0x90000000}}
2021/04/17 06:26:16 bess.go:249: setUpfInfo bess
2021/04/17 06:26:16 bess.go:253: IP pool :  10.250.0.0/16
2021/04/17 06:26:16 main.go:114: Access  IP:  198.18.0.1
2021/04/17 06:26:16 main.go:114: Core  IP:  198.19.0.1
2021/04/17 06:26:16 bess.go:279: bessIP  localhost:10514
2021/04/17 06:26:16 pfcpsim.go:30: sent heartbeat request to: 127.0.0.1:8805
2021/04/17 06:26:16 pfcpsim.go:53: sent association setup request to: 127.0.0.1:8805
2021/04/17 06:26:16 pfcpsim.go:88: sent PFD management request to: 127.0.0.1:8805
2021/04/17 06:26:16 pfcpsim.go:192: sent session establishment request to: 127.0.0.1:8805
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x912366]

goroutine 1 [running]:
github.com/wmnsk/go-pfcp/ie.(*IE).FSEID(0x0, 0x1e, 0x5dc, 0xc2c8a0)
        /pfcpiface/vendor/github.com/wmnsk/go-pfcp/ie/f-seid.go:27 +0x26
main.createPFCP(0xc00000e030, 0xc000032660, 0x0)
        /pfcpiface/pfcpsim.go:207 +0x21f3
main.pfcpSim()
        /pfcpiface/pfcpsim.go:311 +0x145
main.main()
        /pfcpiface/main.go:154 +0xa5a
```

caused because we dont handle error responses in pfcpsim.

@badhrinathpa can you help with why we are getting request rejected?

[n4.zip](https://github.com/omec-project/upf-epc/files/6328737/n4.zip)

**Comment by mgeiszler** [comment]
@krsna1729 What is the status of this fix being merged with the master branch?
The master branch still has the issue:
`docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -pfcpsim`
`2021/04/30 00:00:12 main.go:127: {sim 50000 {ens803f2} {ens803f3} {172.17.0.1  spgwc false 10.250.0.0/16 8080} {172.17.0.1/32 onos 51001 10.250.0.0/24} false {16.0.0.1 11.1.1.129 13.1.1.199 6.6.6.6 9.9.9.9 0x30000000 0x90000000}}`
`2021/04/30 00:00:12 bess.go:249: setUpfInfo bess`
`2021/04/30 00:00:12 bess.go:253: IP pool :  10.250.0.0/16`
`2021/04/30 00:00:12 main.go:114: Access  IP:  198.18.0.1`
`2021/04/30 00:00:12 main.go:114: Core  IP:  198.19.0.1`
`2021/04/30 00:00:12 bess.go:268: Dest address  172.17.0.1`
`2021/04/30 00:00:12 bess.go:270: SPGWU/UPF address IP:  172.17.0.2`
`2021/04/30 00:00:12 bess.go:279: bessIP  localhost:10514`
`2021/04/30 00:00:12 pfcpsim.go:31: sent heartbeat request to: 127.0.0.1:8805`
`2021/04/30 00:00:12 pfcpsim.go:36: read udp 127.0.0.1:57032->127.0.0.1:8805: recvfrom: connection refused`

**Comment by mgeiszler** [comment]
@krsna1729 What is the status of this change being merged with the master branch?

**Comment by krsna1729** [comment]
@badhrinathpa seems like this fixed it https://github.com/omec-project/upf-epc/commit/7464822e63096fb59d7a06d25474418d0be0c157

Now hitting #267

**Review by badhrinathpa — APPROVED** [review]
+1

**Pull request merged**
