### PR TITLE
Add Makefile and VERSION file for standardized image build

### PR DESCRIPTION
**Pull request by hyunsun**

### CODE REVIEW

**Comment by krsna1729** [comment]
@hyunsun [build.sh](scripts/build.sh) has the targets, referenced by [docker_setup.sh](docker_setup.sh)

**Comment by krsna1729** [comment]
also in github [actions](https://github.com/omec-project/upf-epc/blob/master/.github/workflows/pull_request.yml)

**Comment by hyunsun** [comment]
@zdw This repo will be used in Aether project, soon.

**Comment by krsna1729** [comment]
```
CXXARCHFLAGS ?= -march=native
```
BESS compilation itself has this flag

**Comment by ajamshed** [comment]
> CXXARCHFLAGS ?= -march=native

Saw this late.. Removing this then,

**Pull request merged**
