### PR TITLE
Update README about DDN

### PR DESCRIPTION
**Pull request by pudelkoM**
Update the README to reflect the current state of DDN support

### CODE REVIEW

**Review by badhrinathpa — APPROVED** [review]
+1

**Comment by krsna1729** [comment]
retest this please

**Comment by badhrinathpa** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Review by thakurajayL — APPROVED** [review]

**Comment by yoooou** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
