### PR TITLE
Hash pipeline Improvement

### PR DESCRIPTION
**Pull request by amarsri28**
Hash Pipeline improvement.

1. It improves on memory allocation/usage and initialization - new logic has been made so that every-time buffer need not be initialized in bulk lookup.
2. Table sharing logic - if new hash table create request comes then first its checked if table already exist. if exist reuse it.

### CODE REVIEW

**Comment by krsna1729** [comment]
@amarsri28 split 1 and 2 into separate PRs. For 2 is there something in BESS we can leverage like this
https://github.com/NetSys/bess/blob/master/core/shared_obj.h

**Comment by krsna1729** [comment]
Superseded by #226 and future PRs

**Comment by amarsri28** [comment]
this Pr contain changes which need to be merged so opening now for updation.

**Comment by amarsri28** [comment]
comment

**Review by krsna1729 — APPROVED** [review]

**Pull request merged**
