### PR TITLE
Added NTF to new pipeline

### PR DESCRIPTION
**Pull request by nevelis**
Network token function added to the new pipeline & configuration, with a single in/out gate on the NTF module.

If NTF is enabled in sim mode, 1000/5000 flows will have tokens, with roughly 1/6th of the packets being a STUN packet with a network token in it.  This is not a realistic scenario - in practice there will be far less network token packets being sent, but given the limitations of the Source module and Rewrite module (32 packet templates max), this is the best we can do for the least effort that verifies things are working.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by krsna1729** [comment]
Test this please

**Comment by krsna1729** [comment]
squash and rebase

**Comment by krsna1729** [comment]
@nevelis it did not seem to have rebased correctly
image

**Comment by nevelis** [comment]
@krsna1729 I think it's rebased correctly now but it's failing on container push.  Is there anything I need to do here?

**Comment by yoooou** [comment]
retest this please

**Comment by krsna1729** [comment]
>  it's failing on container push. Is there anything I need to do here?
Same reason as before - we dont have a bot yet and you dont have write creds for this repo

**Comment by krsna1729** [comment]
@nevelis there is no change in upf.json can you remove from the PR?

**Comment by nevelis** [comment]
> @nevelis there is no change in upf.json can you remove from the PR?

The change to upf.json fixes the inconsistent use of leading tabs & spaces for indentation which was triggering me due to my different indentation settings :) I can revert this though, what do you think?

**Comment by krsna1729** [comment]
that must be somebody's emacs :P
Lets have it in the PR. thanks!

**Pull request merged**
