### PR TITLE
Workaround for division by zero crash

### PR DESCRIPTION
**Pull request by ccascone**
We don't know yet the root cause of #376. The crash has been observed multiple times per day on a few production deployments. This is a workaround to prevent the crash while we investigate the root cause.

We don't know how to reproduce the issue, but we know it happens once in a while (tens of minutes to hours after starting bessd). As a consequence, we assume this workaround will be hit only a few times, causing only a few packets to skip the meter and be marked as green. We can better asses the frequency by looking at the new log message.

### CODE REVIEW

**Comment by ccascone** [comment]
Also, the author of the PR knows very little about C, DPDK, and BESS... we ask reviewers to please be gentle :)

**Comment by ccascone** [comment]
this workaround has been running on 3 deployments for more than 24 hours, no crash has been reported since then. I'm planning to merge this soon.

**Comment by amarsri28** [comment]
pls look at the comments given.

**Comment by ccascone** [comment]
@amarsri28 I say the comments on #376. It looks like you don't have any explicit concern with this PR, so I'm going ahead and merge this.

**Review by thakurajayL — APPROVED** [review]

**Comment by ccascone** [comment]
retest this please

**Pull request merged**
