### PR TITLE
Fix flow measure reads in no traffic situations

### PR DESCRIPTION
**Pull request by pudelkoM**
When there is no traffic flowing though the pipeline, the in-band mechanism of attaching the current buffer side to packets can't be used. Instead, we have to flip the flag and tell the module which side to read explicitly from the controller/agent side.

Steps to reproduce:
- Start and simulate: `./docker_setup.sh && docker exec -ti bess-pfcpiface pfcpiface -config /conf/upf.json -simulate create`
- Refresh prometheus page to read stats
- Stop traffic flow: `docker exec -ti bess-pfcpiface pfcpiface -config /conf/upf.json -simulate delete`
- Refresh page again, shows incorrect results

### CODE REVIEW

**Comment by pudelkoM** [comment]
restest this please

**Review by ccascone — APPROVED** [review]
+1 on the methodology. I'll let @osinstom approve the `pfcpiface` changes.

~Would it make sense to formalize the `steps to reproduce` into a PTF linerate test?~

**Comment by ccascone** [comment]
Ignore the comment about the linerate tests... I forgot we don't test PFCP-Agent.

**Comment by pudelkoM** [comment]
retest this please

**Pull request merged**
