### PR TITLE
Enable re-registration of Prometheus metrics and HTTP endpoints

### PR DESCRIPTION
**Pull request by osinstom**
Integration tests must Run() and Stop() PFCPIface several times, but the current version of pfcpiface doesn't allow to re-register Prometheus/HTPP endpoints. Fix that by:
- using `promauto` package to automatically register Prometheus endpoints
- using `NewServeMux()` that allows for re-registration of HTTP handles

### CODE REVIEW

**Comment by pudelkoM** [comment]
Do we _want_ to keep `PFCPIface` state between tests? Is creating a new instance per test undesirable?

**Comment by osinstom** [comment]
> Do we _want_ to keep `PFCPIface` state between tests? Is creating a new instance per test undesirable?

We may have to change configuration between tests.

**Comment by pudelkoM** [comment]
> We may have to change configuration between tests.

My point was, if calling `Run()` and `Stop()` on the same `PFCPIface` instance is a problem, can we create new instances instead?

**Comment by osinstom** [comment]
> > We may have to change configuration between tests.
> 
> My point was, if calling `Run()` and `Stop()` on the same `PFCPIface` instance is a problem, can we create new instances instead?

Ok, got it now - and I agree, we can do that.

**Pull request closed without merging**
